cfg_car_Num: 'CDD10-4' #车辆名称
# 地图ID
cfg_Map_ID: 2
locator_ip: "192.168.137.104"  #雷达ip
scheduler_ip: "192.168.1.185"  #服务器ip
ad_modular_ip: "192.168.137.204"   #AD模块ip
fork_height_list: [0.08, 0.132, 0.256, 0.388, 0.699, 1.367]  #货叉高度和AD模块的对应值
fork_ad_list: [292, 459, 893, 1391, 2628, 5306]
# 光电开关启用
laser_switch: True
# 避障雷达启用
radar_switch: False
# 雷达数量
radar_num: 2
# 货物检测开关
fork_switch: False

# 以下参数非必要请勿修改
cfg_nav350_edgeoffset: {front:1.80, behind: 0.95, left: 0.96,right: 0.96}
cfg_nav350_goodoffset: 1.013   #雷达与从动轮的距离
wheelBase: 0.973 #轴距
wheel_angle_drift: -0.00 # 舵轮偏移，弧度制
locator_drift: -0.00    # 雷达偏移
cfg_forkup_speed_255: 0.1  # 全速上升速度
cfg_forkdown_speed_255: -0.102  # 全速下降速度

# 舵轮90（左）（MOTEC-绝对位置）
cfg_position_zero_L: -10485760  #YHL or YUFENGPANDA   对应编码器的值
# 舵轮90（右）（MOTEC-绝对位置）
cfg_position_zero_R: 10485760 #YHL or YUFENGPANDA
# 直线长度
slow_down_straight_len: 1
slow_down_straight_to_turn_len: 1